layout_spectrum: 0.493617
typography_spectrum: 0.3468085
color:
  lightness: 0.8851064
  brandStrength: 0.07716516
  saturation: 0.5787234
  rhythmicContrast: 0.6574468
  brandColors:
    - '#050404'
    - '#FFFFFF'
    - '#912727'
    - '#9BAAAC'
    - '#FB4C4A'
name: Kansascityhorseproperty
